name: PROD Deploy Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão/Tag para Deploy (ex: 1.1.0)'
        required: true
        default: '1.0.0'
        type: string
      environment:
        description: 'Ambiente de destino'
        required: true
        default: 'Production'
        type: choice
        options:
          - Production
          - Staging

jobs:
  deploy:
    name: Executar Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up JDK 25 e Configurar Autenticação
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        server-id: github # Cria a ponte de autenticação no arquivo settings.xml gerado pelo GitHub
        settings-path: ${{ github.workspace }}

    - name: Baixar o JAR do GitHub Packages
      run: |
        echo "⬇️ Baixando a versão ${{ inputs.version }} do GitHub Packages..."
        
        mvn dependency:get \
          -s $GITHUB_WORKSPACE/settings.xml \
          -DremoteRepositories=github::::https://maven.pkg.github.com/${{ github.repository_owner }}/shortenator-backend \
          -Dartifact=com.cviana:shortenator-backend:${{ inputs.version }}:jar \
          -Dtransitive=false
      env:
        GITHUB_TOKEN: ${{ github.token }}